= Complete API documentation

link:../index.html[Back to documentation home]

== Update database

Fetch data from data.gouv.fr

=== Full update

operation::update/full[snippets='httpie-request,http-response']

=== Partial update

operation::update/since[snippets='httpie-request,request-parameters,http-response']

== Locality

French departments and regions

=== Some stats

operation::locality/stats[snippets='httpie-request,http-response']

=== Department by code

If the department exists

operation::locality/department-code-exists[snippets='httpie-request,http-response']


If the department does not exists

operation::locality/department-code-does-not-exist[snippets='httpie-request,http-response']

=== Region by code

If the region exists

operation::locality/region-code-exists[snippets='httpie-request,http-response']

If the region does not exists

operation::locality/region-code-does-not-exist[snippets='httpie-request,http-response']

=== Serach regions and departments

operation::locality/regions-all[snippets='httpie-request,http-response']

operation::locality/regions-search[snippets='httpie-request,http-response']

operation::locality/departments-all[snippets='httpie-request,http-response']

operation::locality/departments-search[snippets='httpie-request,http-response']

