= Complete API documentation

link:../index.html[Back to documentation home]

== Update database

Fetch data from data.gouv.fr

==== Full update
[%collapsible]
======
operation::update/full-accepted[snippets='http-request']

If the update is accepted:

operation::update/full-accepted[snippets='http-response']

operation::update/full-rejected[snippets='http-response']

operation::update/full-rejected[snippets='response-fields']
======

=== Partial update

operation::update/since[snippets='http-request,request-parameters,http-response,response-fields']

operation::update/days[snippets='http-request,request-parameters,http-response,response-fields']

=== Automatic update

operation::update/auto[snippets='http-request,request-parameters,http-response,response-fields']

== Locality

French departments and regions

=== Regions

==== Region by ID

operation::locality/region-id-exists[snippets='http-request,path-parameters,http-response,response-fields']

==== Region by code

operation::locality/region-code-exists[snippets='http-request,path-parameters,http-response,response-fields']

==== All regions

operation::locality/regions-all[snippets='http-request,http-response,response-fields']

==== Search regions

operation::locality/regions-search[snippets='http-request,request-parameters,http-response,response-fields']

=== Departments

==== Department by ID

operation::locality/department-id-exists[snippets='http-request,path-parameters,http-response,response-fields']

==== Department by code

operation::locality/department-code-exists[snippets='http-request,path-parameters,http-response,response-fields']

==== All departments

operation::locality/departments-all[snippets='http-request,http-response,response-fields']

==== Search departments

operation::locality/departments-search[snippets='http-request,request-parameters,http-response,response-fields']

//=== Some stats
//
//operation::locality/stats[snippets='httpie-request,http-response']
//
//=== Department by code
//
//If the department exists
//
//operation::locality/department-code-exists[snippets='httpie-request,http-response']
//
//
//If the department does not exists
//
//operation::locality/department-code-does-not-exist[snippets='httpie-request,http-response']
//
//=== Region by code
//
//If the region exists
//
//operation::locality/region-code-exists[snippets='httpie-request,http-response']
//
//If the region does not exists
//
//operation::locality/region-code-does-not-exist[snippets='httpie-request,http-response']
//
//=== Serach regions and departments
//
//operation::locality/regions-all[snippets='httpie-request,http-response']
//
//operation::locality/regions-search[snippets='httpie-request,http-response']
//
//operation::locality/departments-all[snippets='httpie-request,http-response']
//
//operation::locality/departments-search[snippets='httpie-request,http-response']
//
